# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-17 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lanliuser',
            name='attended_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendants', to='core.Class'),
        ),
    ]
