# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-17 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180317_0330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': '班级', 'verbose_name_plural': '班级'},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name': '年级', 'verbose_name_plural': '年级'},
        ),
        migrations.AlterModelOptions(
            name='lanliuser',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AlterModelOptions(
            name='lecture',
            options={'verbose_name': '讲座', 'verbose_name_plural': '讲座'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': '通知', 'verbose_name_plural': '通知'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': '学校', 'verbose_name_plural': '学校'},
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='name',
        ),
        migrations.AddField(
            model_name='lecture',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='标题'),
            preserve_default=False,
        ),
    ]
