# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-17 13:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180317_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='expired_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 17, 13, 50, 51, 487539, tzinfo=utc), verbose_name='过期时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='core.Grade', verbose_name='年级名'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='core.School', verbose_name='学校名'),
        ),
        migrations.AlterField(
            model_name='lanliuser',
            name='attended_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendants', to='core.Class'),
        ),
        migrations.AlterField(
            model_name='lanliuser',
            name='attended_lectures',
            field=models.ManyToManyField(blank=True, related_name='attendants', to='core.Lecture'),
        ),
        migrations.AlterField(
            model_name='lanliuser',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='lanliuser',
            name='last_login_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 17, 13, 51, 45, 196172, tzinfo=utc), verbose_name='上次登录时间'),
            preserve_default=False,
        ),
    ]
