# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-17 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180317_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lanliuser',
            name='last_login_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='上次登录时间'),
        ),
    ]
