# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-05 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180317_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='lanliuser',
            name='avatar',
            field=models.CharField(blank=True, max_length=200, verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='lanliuser',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='城市'),
        ),
        migrations.AddField(
            model_name='lanliuser',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='国家'),
        ),
        migrations.AddField(
            model_name='lanliuser',
            name='province',
            field=models.CharField(blank=True, max_length=50, verbose_name='省份'),
        ),
        migrations.AlterField(
            model_name='lanliuser',
            name='sex',
            field=models.IntegerField(choices=[(1, '男'), (2, '女'), (0, '未知')], default=1, verbose_name='性别'),
        ),
    ]
